force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Tesla</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
            <value>
                <fullName>Infiniti</fullName>
            </value>
            <value>
                <fullName>Jeep</fullName>
            </value>
            <value>
                <fullName>Volvo</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Lamborghini</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Car_Rental_Garage__c.field-meta.xml
<CustomField>
    <fullName>Car_Rental_Garage__c</fullName>
    <label>Car Rental Garage</label>
    <referenceTo>Car_Rental_Garage__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Rental_Garage__c/Car_Rental_Garage__c.object-meta.xml
<CustomObject>
    <label>Car Rental Garage</label>
    <nameField>
        <label>Car Rental Garage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Rental Garages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Rental_Garage__c/fields/Car_Rental_Office__c.field-meta.xml
<CustomField>
    <fullName>Car_Rental_Office__c</fullName>
    <label>Car Rental Office</label>
    <referenceTo>Car_Rental_Office__c</referenceTo>
    <relationshipLabel>Car Rental Garages</relationshipLabel>
    <relationshipName>Car_Rental_Garages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Rental_Office__c/Car_Rental_Office__c.object-meta.xml
<CustomObject>
    <label>Car Rental Office</label>
    <nameField>
        <label>Car Rental Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Rental Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CarHandlerDataFactory.cls
public with sharing class CarHandlerDataFactory {

    private static String OFFICE_NAME = 'TestOffice';
    private static String GARAGE_NAME = 'TestGarage';


    public static Car__c getCarByName(String name) {
        return new Car__c(Name = name, Brand__c = 'Mercedes-Benz', Price__c = 100000);
    }

    public static List<Car__c> getCars(Integer countOfCarsNeed) {
        Car_Rental_Office__c office = new Car_Rental_Office__c(Name = OFFICE_NAME);
        insert office;
        Id officeId = [SELECT Id FROM Car_Rental_Office__c].Id;

        Car_Rental_Garage__c garage = new Car_Rental_Garage__c(Name = GARAGE_NAME, Car_Rental_Office__c = officeId, Phone__c = '+30011111111', Email__c = 'mail@office.com');
        insert garage;
        Id garageId = [SELECT Id FROM Car_Rental_Garage__c].Id;

        List<Car__c> cars = new List<Car__c>();
        for (Integer i = 0; i < countOfCarsNeed; i++) {
            cars.add(new Car__c(Name = 'Test_' + i, Brand__c = 'Volkswagen', Car_Rental_Garage__c = garageId, Price__c = i * 1000));
        }

        return cars;
    }

    public static String getOfficeName() {
        return OFFICE_NAME;
    }

    public static String getGarageName() {
        return GARAGE_NAME;
    }
}