force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Car_Rental_Garage__c.field-meta.xml
<CustomField>
    <fullName>Car_Rental_Garage__c</fullName>
    <label>Car Rental Garage</label>
    <referenceTo>Car_Rental_Garage__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Rental_Garage__c/Car_Rental_Garage__c.object-meta.xml
<CustomObject>
    <label>Car Rental Garage</label>
    <nameField>
        <label>Car Rental Garage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Rental Garages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Rental_Garage__c/fields/Car_Rental_Office__c.field-meta.xml
<CustomField>
    <fullName>Car_Rental_Office__c</fullName>
    <label>Car Rental Office</label>
    <referenceTo>Car_Rental_Office__c</referenceTo>
    <relationshipLabel>Car Rental Garages</relationshipLabel>
    <relationshipName>Car_Rental_Garages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Rental_Office__c/Car_Rental_Office__c.object-meta.xml
<CustomObject>
    <label>Car Rental Office</label>
    <nameField>
        <label>Car Rental Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Rental Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Rental_Office__c/fields/Number_Of_Related_Cars__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Related_Cars__c</fullName>
    <label>Number Of Related Cars</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FutureMethodsTest.cls
@isTest
public with sharing class FutureMethodsTest {

    private static Integer COUNT_OF_CARS_TO_CREATE = 4;

    @testSetup
    public static void setup() {
        insert CarHandlerDataFactory.getCars(COUNT_OF_CARS_TO_CREATE);
    }

    @isTest
    public static void countRelatedCarsToOfficeTest() {
        String carName = 'TestName';
        String officeName = CarHandlerDataFactory.getOfficeName();
        String garageName = CarHandlerDataFactory.getGarageName();

        Car_Rental_Garage__c testGarage = [SELECT Id, Name FROM Car_Rental_Garage__c WHERE Name =: garageName];

        Car__c newCar = CarHandlerDataFactory.getCarByName(carName);
        newCar.Car_Rental_Garage__c = testGarage.Id;

        Test.startTest();

        insert newCar;
        // get office to set wrong value and execute future method to recount related cars to the office
        Car_Rental_Office__c office = [SELECT Id, Name, Number_Of_Related_Cars__c FROM Car_Rental_Office__c WHERE Name =: officeName];
        office.Number_Of_Related_Cars__c = 0;
        update office;

        List<Car__c> cars = [SELECT Id FROM Car__c];
        List<Id> carIdList = new List<Id>();
        for (Car__c car_i : cars) {
            carIdList.add(car_i.Id);
        }
        
        FutureMethods.countRelatedCarsToOffice(carIdList);

        Test.stopTest();

        Car_Rental_Office__c officeFromDb = [SELECT Id, Name, Number_Of_Related_Cars__c FROM Car_Rental_Office__c WHERE Name =: officeName];

        System.assertEquals(COUNT_OF_CARS_TO_CREATE + 1, officeFromDb.Number_Of_Related_Cars__c, 'Wrong count of cars on office record');
    }
}