force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Car_Rental_Garage__c.field-meta.xml
<CustomField>
    <fullName>Car_Rental_Garage__c</fullName>
    <label>Car Rental Garage</label>
    <referenceTo>Car_Rental_Garage__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Rental_Garage__c/Car_Rental_Garage__c.object-meta.xml
<CustomObject>
    <label>Car Rental Garage</label>
    <nameField>
        <label>Car Rental Garage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Rental Garages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Rental_Garage__c/fields/Car_Rental_Office__c.field-meta.xml
<CustomField>
    <fullName>Car_Rental_Office__c</fullName>
    <label>Car Rental Office</label>
    <referenceTo>Car_Rental_Office__c</referenceTo>
    <relationshipLabel>Car Rental Garages</relationshipLabel>
    <relationshipName>Car_Rental_Garages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Rental_Office__c/Car_Rental_Office__c.object-meta.xml
<CustomObject>
    <label>Car Rental Office</label>
    <nameField>
        <label>Car Rental Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Rental Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Rental_Office__c/fields/Number_Of_Related_Cars__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Related_Cars__c</fullName>
    <label>Number Of Related Cars</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CountOfRelatedCarsToOfficeBatch.cls
public with sharing class CountOfRelatedCarsToOfficeBatch implements Database.Batchable<SObject>, Schedulable {
   
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new CountOfRelatedCarsToOfficeBatch(), 200);
    }
   
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Car_Rental_Garage__c FROM Car__c';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Car__c> scope) {
        Set<Id> garagesId = new Set<Id>();
        for(Car__c car_i : scope) {
            garagesId.add(car_i.Car_Rental_Garage__c);
        }
        Map<Id, Car_Rental_Garage__c> garageRecordsMap = new Map<Id, Car_Rental_Garage__c>([SELECT Car_Rental_Office__c FROM Car_Rental_Garage__c WHERE Id IN :garagesId]);
        Set<Id> officesIdSet = new Set<Id>();
        
        for (Car_Rental_Garage__c garage_i : garageRecordsMap.values()) {
            officesIdSet.add(garage_i.Car_Rental_Office__c);
        }
        
        Map<Id, Car_Rental_Office__c> officeRecordsMap = new Map<Id, Car_Rental_Office__c>([SELECT Id, Number_Of_Related_Cars__c FROM Car_Rental_Office__c WHERE Id IN : officesIdSet]);
        Set<Car_Rental_Office__c> officeSet = new Set<Car_Rental_Office__c>();

        for(Car_Rental_Office__c office_i : officeRecordsMap.values()) {
            officeSet.add(office_i);
        }

        List<AggregateResult> aggrs = [SELECT Car_Rental_Garage__r.Car_Rental_Office__c, count(Id) carNum
                                       FROM Car__c
                                       WHERE Active__c = true AND Car_Rental_Garage__r.Car_Rental_Office__c IN: officesIdSet
                                       GROUP BY Car_Rental_Garage__r.Car_Rental_Office__c];

        for (AggregateResult aggr : aggrs) {

            Id officeId = (id) aggr.get('Car_Rental_Office__c');
            Car_Rental_Office__c office = officeRecordsMap.get(officeId);
            if (officeSet.contains(office)) {
                officeSet.remove(office);
            }
            Decimal newValue = (Decimal) aggr.get('carNum');

            if (office.Number_Of_Related_Cars__c != newValue) {
                officeRecordsMap.get(officeId).Number_Of_Related_Cars__c = newValue;
            }
        }
        
        for (Car_Rental_Office__c office_i : officeSet) {
            office_i.Number_Of_Related_Cars__c = 0;
        }

        update new List<Car_Rental_Office__c>(officeSet);
        update officeRecordsMap.values();
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('CountOfRelatedCarsToOfficeBatch is done, ' + DateTime.now());
    }
}

// String cronExp = '0 0 0 ? * * *';
// System.Schedule('CountOfRelatedCarsToOfficeBatch', cronExp, new CountOfRelatedCarsToOfficeBatch());